[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "airt"
version = "0.1.0"
description = "AiRT core library"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["airt"]
